In [27]:
import pandas as pd

file_path = '../data/2024_Finaccess_Publicdata.xlsx'

# Load the full survey dataset (this is the heavy operation that takes a few minutes)
#df = pd.read_excel(file_path, sheet_name='2024_Finaccess_Publicdata')

print("Dataset loaded successfully!")
print("Shape:", df.shape)

Dataset loaded successfully!
Shape: (20871, 3816)

In [28]:
# Convert all object/mixed-type columns to strings to satisfy Parquet requirements
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].astype(str)

# Now save to Parquet successfully
#df.to_parquet('data/finaccess_2024.parquet', index=False)
print("Dataset successfully saved to Parquet!")

Dataset successfully saved to Parquet!

In [29]:
# For all future sessions, you can skip the Excel load and run this in 3 seconds:
df = pd.read_parquet('data/finaccess_2024.parquet')

print("Columns:", df.columns.tolist()[:20])
display(df.head())

Columns: ['interview__key', 'interview__id', 'county', 'A07', 'A08', 'A10', 'Interview_Status', 'A9i', 'Z1', 'A13', 'A12ii_length', 'A14iv', 'A14vi', 'FHH_Spouse', 'A15a', 'A15i', 'A18', 'A19', 'A14i', 'A14ii']

,interview__key,interview__id,county,A07,A08,A10,Interview_Status,A9i,Z1,A13,...,sacco_redress,mobilemoney_redress,mobilebank_redress,not_registered_mmoney_24,using_someone_acc,insurance_including_NHIF_use,All_Insurance_excluding_NHIF_use,PWD,Latitude,Longitude
0,21-61-43-44,00005e63e7424aa19e63adb071955233,Garissa,225,Urban,1,Household found with competent respondent,Access granted,completed,Male,...,nan,nan,nan,No,nan,Never used,Never used,Without Disability,-0.435423,39.636586
1,87-78-54-60,000718d26f5942998522033a66594b4c,Garissa,223,Urban,3,Household found with competent respondent,Access granted,completed,Male,...,nan,nan,nan,No,nan,Never used,Never used,Without Disability,0.058794,40.305006
2,32-71-19-84,0008721681d2468aa1ef456bba4475dc,Busia,1514,Urban,3,Household found with competent respondent,Access granted,completed,Female,...,nan,nan,nan,No,nan,Never used,Never used,Without Disability,0.636836,34.277390
3,48-18-78-99,00099e961d49470585c1a7f49fa3b7fb,Kiambu,796,Urban,3,Household found with competent respondent,Access granted,completed,Male,...,nan,nan,nan,No,nan,Never used,Never used,Without Disability,-1.251917,36.719076
4,50-82-98-89,000bb72e959b4dd48443da902c01e920,Murang'a,763,Urban,16,Household found with competent respondent,Access granted,completed,Female,...,nan,nan,nan,No,Yes,Never used,Never used,Without Disability,-0.795820,37.131085

In [30]:
# Load the Variables sheet (the data dictionary)
dictionary_df = pd.read_excel(file_path, sheet_name='Variables')

# Search for columns related to our key themes
# We will look for keywords in the variable labels/descriptions
keywords = ['income', 'farm', 'agriculture', 'mobile money', 'M-Pesa']

# Filter the dictionary to show only rows containing our keywords
search_results = dictionary_df[
    dictionary_df.astype(str).apply(lambda x: x.str.contains('|'.join(keywords), case=False)).any(axis=1)
]

print("Found", len(search_results), "relevant variables.")
display(search_results.head(20))

Found 214 relevant variables.

,position,name,type,isnumeric,format,vallab,varlab
73,74,B1L__5,byte,1,%12.0g,B1L__5,"B1L__5:Machinery, vehicles, equipment, tools f..."
97,98,B3A__1,byte,1,%12.0g,NaN,"B3A. Farming (crops, keeping livestock, fishin..."
110,111,B3Ai,strL,0,%477s,NaN,B3Ai. Income Sources- Other
120,121,B3D__2_1,byte,1,%12.0g,NaN,B3D__2.1: B3D. Received Payments:Mobile money ...
121,122,B3D__3_1,byte,1,%12.0g,NaN,B3D__3.1: B3D. Received Payments:Mobile money ...
135,136,B3D__2_2,byte,1,%12.0g,NaN,B3D__2.2: B3D. Received Payments:Mobile money ...
136,137,B3D__3_2,byte,1,%12.0g,NaN,B3D__3.2: B3D. Received Payments:Mobile money ...
150,151,B3D__2_3,byte,1,%12.0g,NaN,B3D__2.3: B3D. Received Payments:Mobile money ...
151,152,B3D__3_3,byte,1,%12.0g,NaN,B3D__3.3: B3D. Received Payments:Mobile money ...
165,166,B3D__2_4,byte,1,%12.0g,NaN,B3D__2.4: B3D. Received Payments:Mobile money ...
166,167,B3D__3_4,byte,1,%12.0g,NaN,B3D__3.4: B3D. Received Payments:Mobile money ...
180,181,B3D__2_5,byte,1,%12.0g,NaN,B3D__2.5: B3D. Received Payments:Mobile money ...
181,182,B3D__3_5,byte,1,%12.0g,NaN,B3D__3.5: B3D. Received Payments:Mobile money ...
195,196,B3D__2_6,byte,1,%12.0g,NaN,B3D__2.6: B3D. Received Payments:Mobile money ...
196,197,B3D__3_6,byte,1,%12.0g,NaN,B3D__3.6: B3D. Received Payments:Mobile money ...
210,211,B3D__2_7,byte,1,%12.0g,NaN,B3D__2.7: B3D. Received Payments:Mobile money ...
211,212,B3D__3_7,byte,1,%12.0g,NaN,B3D__3.7: B3D. Received Payments:Mobile money ...
225,226,B3D__2_8,byte,1,%12.0g,NaN,B3D__2.8: B3D. Received Payments:Mobile money ...
226,227,B3D__3_8,byte,1,%12.0g,NaN,B3D__3.8: B3D. Received Payments:Mobile money ...
240,241,B3D__2_9,byte,1,%12.0g,NaN,B3D__2.9: B3D. Received Payments:Mobile money ...

In [31]:
vars_df = pd.read_excel('../data/2024_Finaccess_Publicdata.xlsx', sheet_name='Variables')

keywords = ['loan', 'credit', 'borrow', 'debt', 'repay', 'default', 
            'arrears', 'asset', 'machinery', 'equipment', 'solar', 
            'mobile money', 'lend', 'installment']

mask = vars_df['varlab'].str.contains('|'.join(keywords), case=False, na=False) | \
       vars_df['name'].str.contains('|'.join(keywords), case=False, na=False)

relevant_vars = vars_df[mask][['name', 'varlab']]
print(relevant_vars.to_string())

                                  name                                                                            varlab
63                                B1Hi                                                      B1Hi. Source of loans/credit
72                              B1L__4  B1L__4:Machinery, vehicles, equipment, tools, building for business/self-employm
73                              B1L__5     B1L__5:Machinery, vehicles, equipment, tools for farming or raising livestock
102                             B3A__6                                        B3A. Renting, land, house/rooms, equipment
120                           B3D__2_1  B3D__2.1: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
121                           B3D__3_1  B3D__3.1: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
126                           B3D__8_1                       B3D__8.1: B3D. Received Payments:Credit cards / debit cards
135                           B3D__2_2  B3D__2.2: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
136                           B3D__3_2  B3D__3.2: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
141                           B3D__8_2                       B3D__8.2: B3D. Received Payments:Credit cards / debit cards
150                           B3D__2_3  B3D__2.3: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
151                           B3D__3_3  B3D__3.3: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
156                           B3D__8_3                       B3D__8.3: B3D. Received Payments:Credit cards / debit cards
165                           B3D__2_4  B3D__2.4: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
166                           B3D__3_4  B3D__3.4: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
171                           B3D__8_4                       B3D__8.4: B3D. Received Payments:Credit cards / debit cards
180                           B3D__2_5  B3D__2.5: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
181                           B3D__3_5  B3D__3.5: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
186                           B3D__8_5                       B3D__8.5: B3D. Received Payments:Credit cards / debit cards
195                           B3D__2_6  B3D__2.6: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
196                           B3D__3_6  B3D__3.6: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
201                           B3D__8_6                       B3D__8.6: B3D. Received Payments:Credit cards / debit cards
210                           B3D__2_7  B3D__2.7: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
211                           B3D__3_7  B3D__3.7: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
216                           B3D__8_7                       B3D__8.7: B3D. Received Payments:Credit cards / debit cards
225                           B3D__2_8  B3D__2.8: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
226                           B3D__3_8  B3D__3.8: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
231                           B3D__8_8                       B3D__8.8: B3D. Received Payments:Credit cards / debit cards
240                           B3D__2_9  B3D__2.9: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
241                           B3D__3_9  B3D__3.9: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
246                           B3D__8_9                       B3D__8.9: B3D. Received Payments:Credit cards / debit cards
255                          B3D__2_10  B3D__2.10: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Mone
256                          B3D__3_10  B3D__3.10: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bi
261                          B3D__8_10                      B3D__8.10: B3D. Received Payments:Credit cards / debit cards
281                              B3Iii  B3Iii. In the past 12 months, what was the most money you received in one calend
285                              C1_10                                                 C1-10. Registered on Mobile money
347                               C1_3                               C1-3. Savings/keeping through mobile money provider
348                               C1_4            C1-4. Savings at a Sacco / Savings and Credit Cooperative organisation
354                             C1_13a                        C1_13a. Personal loan/business loan from a commercial bank
355                             C1_13b                      C1_13b. Personal loan/business loan from a microfinance bank
357                              C1_14                                                                C1_14. Credit card
358                              C1_15                                                   C1_15. Loan from mobile banking
359                              C1_16             C1_16. Loan from mobile provider (e.g Fuliza loan, Equity's Boostika)
360                              C1_17                                                            C1_17. Loan from Sacco
361                              C1_18                                       C1_18. Loan from a microfinance institution
362                              C1_19                                                              C1_19. Digital loans
363                              C1_20                                                         C1-20. Loan from Shylocks
364                              C1_21                                                    C1-21. Loan from a group/chama
365                              C1_22  C1_22:Loan from a government institution foreducation, agriculture or a developm
366                              C1_23                                                      C1-23 Loan from Hustler Fund
367                              C1_24                                                       C1-24 Loan from an employer
368                              C1_25                                          C1-25. Loan from family/friend/neighbour
369                              C1_26                                                  C1-26. Cash loan from shopkeeper
370                              C1_27                      C1-27. Taking goods and services on credit from a shopkeeper
371                              C1_28  C1_28:Loan / credits from buyer of your harvest / supplier of agricultural input
372                              C1_29                                         C1-29. Loan Lipa polepole / Hire Purchase
373                              C1_30                                                        C1-30. Loan from Insurance
374                              C1_31                     C1-31. Loan to buy / build a house (mortgage), or to buy land
387                              C1_43  C1_43: Digital/crypto/communitycurrencies/ virtual assets Bitcoin, Litcoin, Nuru
388                              C2_15                                                   C2_15. Loan from mobile banking
389                              C2_16                                            C2_16. Loan from mobile money provider
390                              C2_19  C2_19:Take digital loans that you get through the phone that you download throug
391                              C2_23                                                    C2_23. Loan from Hustler Fund?
513                                 E1            E1: Have you applied for and been denied a loan in the last 12 months?
517                              E2__4                                                 E2_4: Mobile money provider (e.g.
519                              E2__6                                                 E2_6: Credit-Only institution  (e
520                              E2__7                    E2_7: Digital loans that you get through App like Branch, Tala
522                              E2__9                                                      E2_9: Shylocks/Money Lenders
523                             E2__10   E2_10: Loan from a government institutions like AFC, HELB,Youth Fund (excluding
530                             E3__16                      the lender did not have float/money at the time of borrowing
541                              E3__5                                                       E3_5: Still had debt to pay
543                              E3__7                                                          E3_7: Bad credit history
544                              E3__8                                                           E3_8: No credit history
555                              E4__1                              E4. :Don't have money/income/job; Can't afford loans
556                              E4__2                                          E4. :I don't know where or how to borrow
557                              E4__3  E4__3:I don't like borrowing/loansdon't benefit me/there are no loan products th
558                              E4__4                                                   E4. :Loans are too risky for me
559                              E4__5                                                 E4. :I don't trust loan providers
563                              E4__9                                                 do not qualify/Bad credit history
569                              E5__2                  E5__2:I can't afford to borrow at the moment/ it's too expensive
570                              E5__3  E5__2:Loans are not benefitting me/there are no loan products that meet my needs
571                              E5__4                                        E5. :Interest rates for loans are too high
572                              E5__5                                           E5. :Loans have become too risky for me
573                              E5__6                                                 E5. :I don't trust loan providers
574                              E5__7                                           E5. :Unethical debt recovery/harassment
579                               E1iA                                         E1iA: Number of bank Loans past 12 months
580                              E1iiA                                           E1iiA: Number of Outstanding bank Loans
581                             E1iiiA                                       E1iiiA: Reason for taking bank loan product
582                       E1iiiA_Other                               E1iiiA: Reason for taking Bank Loan Product; Others
583                              E1ivA                                              E1ivA: Collateral used for Bank Loan
584                        E1ivA_Other                                      E1ivA: Collateral used for Bank Loan; Others
585                               E1vA                                           E1vA: Frequency of bank loan repayments
586                         E1vA_Other                                   E1vA: Frequency of bank loan repayments; Others
587                              E1viA                                       E1viA: Channels used for repaying bank loan
588                        E1viA_Other                               E1viA: Channels used for repaying bank loan; Others
589                             E1viiA                                              E1viiA: Amount of Bank loan borrowed
590                            E1viiiA                                             E1viiiA: Amount of bank loan approved
591                              E1ixA                                           E1ixA:  Date of borrowing the bank loan
592                               E1xA                                                E1xA: Bank Loan Repayment due date
593                              E1xiA                                               E1xiA: Outstanding bank loan amount
594                               E1iB                            E1iB: Number of microfinance bank loans past 12 months
595                              E1iiB                              E1iiB: Number of Outstanding microfinance bank loans
596                             E1iiiB                          E1iiiB: Reason for taking microfinance bank loan product
597                       E1iiiB_Other                  E1iiiB: Reason for taking microfinance bank loan product; Others
598                              E1ivB                                 E1ivB: Collateral used for microfinance bank loan
599                        E1ivB_Other                         E1ivB: Collateral used for microfinance bank loan; Others
600                               E1vB                              E1vB: Frequency of microfinance bank loan repayments
601                         E1vB_Other                      E1vB: Frequency of microfinance bank loan repayments; Others
602                              E1viB                          E1viB: Channels used for repaying microfinance bank loan
603                        E1viB_Other                  E1viB: Channels used for repaying microfinance bank loan; Others
604                             E1viiB                                 E1viiB: Amount of microfinance bank loan borrowed
605                            E1viiiB                                E1viiiB: Amount of microfinance bank loan approved
606                              E1ixB                               E1ixB: Date of borrowing the microfinance bank loan
607                               E1xB                                   E1xB: Microfinance bank loan repayment due date
608                              E1xiB                                  E1xiB: Outstanding microfinance bank loan amount
609                               E1iC                               E1iC: Number of bank overdraft loans past 12 months
610                              E1iiC                                 E1iiC: Number of Outstanding bank overdraft loans
611                             E1iiiC                                     E1iiiC: Reason for taking bank overdraft loan
612                       E1iiiC_Other                     E1iiiC: Reason for taking bank overdraft loan product; Others
613                              E1ivC                                    E1ivC: Collateral used for bank overdraft loan
614                        E1ivC_Other                            E1ivC: Collateral used for bank overdraft loan; Others
615                               E1vC                                 E1vC: Frequency of bank overdraft loan repayments
616                         E1vC_Other                         E1vC: Frequency of bank overdraft loan repayments; Others
617                              E1viC                             E1viC: Channels used for repaying bank overdraft loan
618                        E1viC_Other                     E1viC: Channels used for repaying bank overdraft loan; Others
619                             E1viiC                                    E1viiC: Amount of bank overdraft loan borrowed
620                            E1viiiC                                   E1viiiC: Amount of bank overdraft loan approved
621                              E1ixC                                 E1ixC:  Date of borrowing the bank overdraft loan
622                               E1xC                                      E1xC: Bank overdraft loan repayment due date
623                              E1xiC                                     E1xiC: Outstanding bank overdraft loan amount
624                               E1iD                                   E1iD: Number of creditcard loans past 12 months
625                             E1iiiD                                 E1iiiD: Reason for taking creditcard loan product
626                       E1iiiD_Other                                 E1iiiD: Reason for taking creditcard loan; Others
627                               E1vD                                     E1vD: Frequency of creditcard loan repayments
628                         E1vD_Other                             E1vD: Frequency of creditcard loan repayments; Others
629                              E1viD                                 E1viD: Channels used for repaying creditcard loan
630                        E1viD_Other                         E1viD: Channels used for repaying creditcard loan; Others
631                             E1viiD                                        E1viiD: Amount of creditcard loan borrowed
632                            E1viiiD                                       E1viiiD: Amount of creditcard loan approved
633                              E1ixD                                      E1ixD: Date of borrowing the creditcard loan
634                               E1xD                                          E1xD: Creditcard loan repayment due date
635                               E1iE                               E1iE: Number of mobile banking loans past 12 months
636                              E1iiE                                 E1iiE: Number of Outstanding mobile banking loans
637                             E1iiiE                             E1iiiE: Reason for taking mobile banking loan product
638                       E1iiiE_Other                     E1iiiE: Reason for taking mobile banking loan product; Others
639                               E1vE                                 E1vE: Frequency of mobile banking loan repayments
640                         E1vE_Other                         E1vE: Frequency of mobile banking loan repayments; Others
641                             E1viiE                                    E1viiE: Amount of mobile banking loan borrowed
642                            E1viiiE                                   E1viiiE: Amount of mobile banking loan approved
643                              E1ixE                                  E1ixE: Date of borrowing the mobile banking loan
644                               E1xE                                      E1xE: Mobile banking loan repayment due date
645                              E1xiE                                     E1xiE: Outstanding mobile banking loan amount
646                               E1iF                        E1iF: Number of mobile money provider loans past 12 months
647                              E1iiF                          E1iiF: Number of Outstanding mobile money provider loans
648                             E1iiiF                      E1iiiF: Reason for taking mobile money provider loan product
649                       E1iiiF_Other              E1iiiF: Reason for taking mobile money provider loan product; Others
650                             E1viiF                             E1viiF: Amount of mobile money provider loan borrowed
651                            E1viiiF                            E1viiiF: Amount of mobile money provider loan approved
652                              E1ixF                           E1ixF: Date of borrowing the mobile money provider loan
653                              E1xiF                              E1xiF: Outstanding mobile money provider loan amount
654                               E1iG                                        E1iG: Number of Sacco loans past 12 months
655                              E1iiG                                          E1iiG: Number of outstanding Sacco Loans
656                             E1iiiG                                      E1iiiG: Reason for taking Sacco loan product
657                       E1iiiG_Other                                      E1iiiG: Reason for taking Sacco loan; Others

In [32]:
pd.set_option('display.max_rows', None)
relevant_vars.to_csv('data/relevant_vars.csv', index=False)

In [33]:
import os
os.makedirs('data', exist_ok=True)

In [34]:
import pandas as pd
vars_df = pd.read_excel('../data/2024_Finaccess_Publicdata.xlsx', sheet_name='Variables')

keywords = ['loan', 'credit', 'borrow', 'debt', 'repay', 'default', 
            'arrears', 'asset', 'machinery', 'equipment', 'solar', 
            'mobile money', 'lend', 'installment', 'food', 'income']

mask = vars_df['varlab'].str.contains('|'.join(keywords), case=False, na=False) | \
       vars_df['name'].str.contains('|'.join(keywords), case=False, na=False)

relevant_vars = vars_df[mask][['name', 'varlab']]
pd.set_option('display.max_rows', None)
relevant_vars.to_csv('data/relevant_vars.csv', index=False)
print("Saved relevant_vars.csv successfully!")

Saved relevant_vars.csv successfully!

In [35]:
b1_vars = vars_df[vars_df['name'].str.startswith('B1', na=False)][['name', 'varlab']]
b1_vars.to_csv('data/b1_vars.csv', index=False)
print(f"Saved {len(b1_vars)} B1 variables to data/b1_vars.csv")

Saved 41 B1 variables to data/b1_vars.csv

In [36]:
repay_keywords = ['repay', 'overdue', 'behind', 'missed', 'struggl', 'difficult', 'arrear', 'default', 'unable to pay']
repay_mask = vars_df['varlab'].str.contains('|'.join(repay_keywords), case=False, na=False)
repay_vars = vars_df[repay_mask][['name', 'varlab']]
print(repay_vars.to_string())

                                 name                                                                            varlab
36                               A24i                                                            A24i Difficulty seeing
37                              A24ii                                                           A24i Difficulty hearing
38                             A24iii                                                           A24i Difficulty walking
39                              A24iv                                                    A24i Difficulty with cognition
40                               A24v                                                     A24i Difficulty with selfcare
41                              A24vi                                               A24i Difficulty with  communicating
52                               B1E1                                                B1E-Unable to pay expenses Housing
53                               B1E2                          B1E-Unable to pay expenses Energy for heating or cooking
54                               B1E3                         B1E-Unable to pay expenses Water for drinking or cleaning
55                               B1E4                                   B1E-Unable to pay expenses Transportation costs
585                              E1vA                                           E1vA: Frequency of bank loan repayments
586                        E1vA_Other                                   E1vA: Frequency of bank loan repayments; Others
587                             E1viA                                       E1viA: Channels used for repaying bank loan
588                       E1viA_Other                               E1viA: Channels used for repaying bank loan; Others
592                              E1xA                                                E1xA: Bank Loan Repayment due date
600                              E1vB                              E1vB: Frequency of microfinance bank loan repayments
601                        E1vB_Other                      E1vB: Frequency of microfinance bank loan repayments; Others
602                             E1viB                          E1viB: Channels used for repaying microfinance bank loan
603                       E1viB_Other                  E1viB: Channels used for repaying microfinance bank loan; Others
607                              E1xB                                   E1xB: Microfinance bank loan repayment due date
615                              E1vC                                 E1vC: Frequency of bank overdraft loan repayments
616                        E1vC_Other                         E1vC: Frequency of bank overdraft loan repayments; Others
617                             E1viC                             E1viC: Channels used for repaying bank overdraft loan
618                       E1viC_Other                     E1viC: Channels used for repaying bank overdraft loan; Others
622                              E1xC                                      E1xC: Bank overdraft loan repayment due date
627                              E1vD                                     E1vD: Frequency of creditcard loan repayments
628                        E1vD_Other                             E1vD: Frequency of creditcard loan repayments; Others
629                             E1viD                                 E1viD: Channels used for repaying creditcard loan
630                       E1viD_Other                         E1viD: Channels used for repaying creditcard loan; Others
634                              E1xD                                          E1xD: Creditcard loan repayment due date
639                              E1vE                                 E1vE: Frequency of mobile banking loan repayments
640                        E1vE_Other                         E1vE: Frequency of mobile banking loan repayments; Others
644                              E1xE                                      E1xE: Mobile banking loan repayment due date
660                              E1vG                                          E1vG: Frequency of Sacco loan repayments
661                        E1vG_Other                                  E1vG: Frequency of Sacco loan repayments; Others
662                             E1viG                                      E1viG: Channels used for repaying Sacco loan
663                       E1viG_Other                              E1viG: Channels used for repaying Sacco loan; Others
667                              E1xG                                               E1xG: Sacco Loan Repayment due date
675                              E1vH                                            E1vH: Frequency of MFI loan repayments
676                        E1vH_Other                                    E1vH: Frequency of MFI loan repayments; Others
677                             E1viH                                        E1viH: Channels used for repaying MFI loan
678                       E1viH_Other                                E1viH: Channels used for repaying MFI loan; Others
682                              E1xH                                                 E1xH: MFI Loan Repayment due date
688                              E1vI                                        E1vI: Frequency of Digital loan repayments
689                        E1vI_Other                                E1vI: Frequency of Digital loan repayments; Others
690                             E1viI                                    E1viI: Channels used for repaying Digital loan
691                       E1viI_Other                            E1viI: Channels used for repaying Digital loan; Others
695                              E1xI                                             E1xI: Digital Loan Repayment due date
703                              E1vJ                                        E1vJ: Frequency of Shylock loan repayments
704                        E1vJ_Other                                E1vJ: Frequency of Shylock loan repayments; Others
705                             E1viJ                                    E1viJ: Channels used for repaying Shylock loan
706                       E1viJ_Other                            E1viJ: Channels used for repaying Shylock loan; Others
710                              E1xJ                                             E1xJ: Shylock Loan Repayment due date
718                              E1vK                                    E1vK: Frequency of Group/Chama loan repayments
719                        E1vK_Other                            E1vK: Frequency of Group/Chama loan repayments; Others
720                             E1viK                                E1viK: Channels used for repaying Group/Chama loan
721                       E1viK_Other                        E1viK: Channels used for repaying Group/Chama loan; Others
725                              E1xK                                         E1xK: Group/Chama Loan Repayment due date
733                              E1vL                         E1vL: Frequency of Government Institution loan repayments
734                        E1vL_Other                 E1vL: Frequency of Government Institution loan repayments; Others
735                             E1viL                     E1viL: Channels used for repaying Government Institution loan
736                       E1viL_Other             E1viL: Channels used for repaying Government Institution loan; Others
740                              E1xL                              E1xL: Government Institution Loan Repayment due date
746                              E1vM                                    E1vM: Frequency of Hustlerfund loan repayments
747                        E1vM_Other                            E1vM: Frequency of Hustlerfund loan repayments; Others
748                             E1viM                                E1viM: Channels used for repaying Hustlerfund loan
749                       E1viM_Other                        E1viM: Channels used for repaying Hustlerfund loan; Others
753                              E1xM                                         E1xM: Hustlerfund Loan Repayment due date
759                              E1vN                                       E1vN: Frequency of Employer loan repayments
760                        E1vN_Other                               E1vN: Frequency of Employer loan repayments; Others
761                             E1viN                                   E1viN: Channels used for repaying Employer loan
762                       E1viN_Other                           E1viN: Channels used for repaying Employer loan; Others
766                              E1xN                                            E1xN: Employer Loan Repayment due date
772                              E1vO                        E1vO: Frequency of Family/Friend/Neighbour loan repayments
773                        E1vO_Other                E1vO: Frequency of Family/Friend/Neighbour loan repayments; Others
774                             E1viO                    E1viO: Channels used for repaying Family/Friend/Neighbour loan
775                       E1viO_Other            E1viO: Channels used for repaying Family/Friend/Neighbour loan; Others
779                              E1xO                             E1xO: Family/Friend/Neighbour Loan Repayment due date
787                              E1vP                                     E1vP: Frequency of Shopkeeper loan repayments
788                        E1vP_Other                             E1vP: Frequency of Shopkeeper loan repayments; Others
789                             E1viP                                 E1viP: Channels used for repaying Shopkeeper loan
790                       E1viP_Other                         E1viP: Channels used for repaying Shopkeeper loan; Others
794                              E1xP                                          E1xP: Shopkeeper Loan Repayment due date
799                              E1vQ       E1vQ: Repayment frequency for goods purchased on credit from the shopkeeper
800                        E1vQ_Other  E1vQ: Repayment frequency for goods purchased on credit from the shopkeeper; Oth
801                             E1viQ   E1viQ: Channels used to repay for goods purchased on credit from the shopkeeper
802                       E1viQ_Other  E1viQ: Channels used to repay for goods purchased on credit from the shopkeeper;
806                              E1xQ         E1xQ: Due date for repaying goods purchased on credit from the shopkeeper
819                              E1vS                    E1vS: Repayment frequency for goods purchased on Hire purchase
820                        E1vS_Other            E1vS: Repayment frequency for goods purchased on Hire purchase; Others
821                             E1viS                E1viS: Channels used to repay for goods purchased on Hire purchase
822                       E1viS_Other        E1viS: Channels used to repay for goods purchased on Hire purchase; Others
833                              E1vT                                      E1vT: Frequency of Insurance loan repayments
834                        E1vT_Other                              E1vT: Frequency of Insurance loan repayments; Others
835                             E1viT                                  E1viT: Channels used for repaying Insurance loan
836                       E1viT_Other                          E1viT: Channels used for repaying Insurance loan; Others
840                              E1xT                                           E1xT: Insurance Loan Repayment due date
848                              E1vU                                       E1vU: Frequency of Mortgage loan repayments
849                        E1vU_Other                               E1vU: Frequency of Mortgage loan repayments; Others
850                             E1viU                                   E1viU: Channels used for repaying Mortgage loan
851                       E1viU_Other                           E1viU: Channels used for repaying Mortgage loan; Others
855                              E1xU                                            E1xU: Mortgage Loan Repayment due date
860                               E2A    E2A: In the past month how much did you spend to repay your outstanding loans?
861                               E2B  E2B: In the past 12 months, did someone in your household repay or help to repay
871                            E2D__1                                                  Borrowed money to repay the loan
872                            E2D__2                                                     Used savings to repaythe loan
873                            E2D__3                                  Sold/gave assets or belongings to repay the loan
874                            E2D__4                            Reduced expenditureson food products to repay the loan
875                            E2D__5                        Reduced expenditures on nonfood products to repay the loan
878                            E2D__8                       Deducted from my monthly pension payments to repay the loan
903                               E2G                                                          E2G: Reasons for Default
915                           E2H__11                                   E2H:Lender agreed to give me more time to repay
941                            E3D__1              E3D: Who in your household did you repay a loan for?:Spouse/ partner
942                            E3D__2                       E3D: Who in your household did you repay a loan for?:Mother
943                            E3D__3                       E3D: Who in your household did you repay a loan for?:Father
944                            E3D__4                     E3D: Who in your household did you repay a loan for?:Daughter
945                            E3D__5                          E3D: Who in your household did you repay a loan for?:Son
946                            E3D__6            E3D: Who in your household did you repay a loan for?:Other relative(s)
947                            E3D__7              E3D: Who in your household did you repay a loan for?:Non relative(s)
948                           E3D__99            E3D: Who in your household did you repay a loan for?:Refused to Answer
2461                         M2ii__11                                                                 Defaulted on loan
2583                           N10__4                                   N10__4:Through dishonesty or default by members
2645                           O5__12                                                       O5_12 To repay a loan/ debt
2695                            P5__3                      P5:High costs of licensing/Difficulty getting license/permit
2696                            P5__4                                P5. Difficulty finding premises location/high cost
2697                            P5__5                  P5:Difficulty paying business expenses (rent, utilities, labour)
2839                          P22__12                                                    Difficulty in getting supplies
2841                          P22__14                                    Difficulty finding premises location/high cost
3007                           Q8a__5                                       Q8a. Difficulty finding inputs (seeds etc.)
3010                           Q8a__8            Q8a__8:Difficulty starting/financingbecause of lack of money (capital)
3011                           Q8a__9                                                 Q8a. Difficulty finding customers
3016                          Q8a__14       Q8a__14:Difficulty getting products to market transport/road infrastructure
3018                          Q8a__16                          Q8a. Difficulty getting paid for products sold on credit
3020                          Q8a__18                                            Q8a. Difficulty in accessing financing
3028                          Q8a__26                                              Difficult in getting licence/permits
3029                          Q8a__27                                  difficulty in management; unavailablity of owner
3145                          Q24__18                                        Lack of skills/difficulty in managing farm
3481                        defaulted                                                           Defaulted on Loans_Debt
3596                    not_difficult                           Not very difficult to access emergency funds in 30 days
3665  Repay_debts_someone_else_credit    To repay debts for someone else who was unable to repay such as family, friend
3666               For_old_age_credit    To repay debts for someone else who was unable to repay such as family, friend

In [38]:
target_col = 'E2E'

# 1. Show the full breakdown
print("Class Balance for E2E (Loan Default/Delinquency status):")
print(df[target_col].value_counts(dropna=False))

# 2. Filter out the "nan" strings and the "Don't know" answers
valid_responses = [
    'I did not default/always pay on time', 
    'Paid late/Missed a payment/Paid less', 
    "Didn't pay at all"
]

# 3. Create the clean modeling dataframe
modeling_df = df[df[target_col].isin(valid_responses)].copy()

print(f"\nFinal clean active borrowers for the model: {modeling_df.shape[0]}")

Class Balance for E2E (Loan Default/Delinquency status):
E2E
nan                                     7720
I did not default/always pay on time    6160
Paid late/Missed a payment/Paid less    5015
Didn't pay at all                       1936
Donâ€™t know                              37
Refused to Answer                          3
Name: count, dtype: int64

Final clean active borrowers for the model: 13111

In [39]:
# 1. Create the binary target: 
# 0 = Always paid on time, 1 = Late/Missed/Defaulted
modeling_df['defaulted'] = modeling_df['E2E'].apply(
    lambda x: 0 if x == 'I did not default/always pay on time' else 1
)

print("--- Binary Target Balance ---")
print(modeling_df['defaulted'].value_counts(normalize=True).round(3))
print("\n")

# 2. Cross-tabulate against specific loan products to find risk drivers
loan_types = {
    'C1_15': 'Mobile Banking Loan',
    'C1_19': 'Digital App Loan',
    'C1_17': 'Sacco Loan'
}

for col, name in loan_types.items():
    if col in modeling_df.columns:
        print(f"--- Default Rate by: {name} ({col}) ---")
        # normalize='index' shows the percentage breakdown row-by-row
        crosstab = pd.crosstab(modeling_df[col], modeling_df['defaulted'], normalize='index').round(3)
        print(crosstab)
        print("\n")
    else:
        print(f"Column {col} not found in current dataframe.\n")

--- Binary Target Balance ---
defaulted
1    0.53
0    0.47
Name: proportion, dtype: float64


--- Default Rate by: Mobile Banking Loan (C1_15) ---
defaulted          0      1
C1_15
Currently use  0.324  0.676
Never used     0.494  0.506
Not stated     1.000  0.000
Used to use    0.463  0.537


--- Default Rate by: Digital App Loan (C1_19) ---
defaulted          0      1
C1_19
Currently use  0.228  0.772
Never used     0.479  0.521
Used to use    0.430  0.570


--- Default Rate by: Sacco Loan (C1_17) ---
defaulted          0      1
C1_17
Currently use  0.631  0.369
Never used     0.455  0.545
Used to use    0.566  0.434

In [40]:
# Get counts AND percentages together, for every C1 loan-type column
c1_cols = [c for c in modeling_df.columns if c.startswith('C1_')]
results = []

for col in c1_cols:
    # Calculate mean (default rate) and count (n)
    counts = modeling_df.groupby(col)['defaulted'].agg(['mean', 'count']).round(3)
    counts.columns = ['default_rate', 'n']
    counts['loan_type'] = col
    
    # Rename the index column so it's clear what the answer was
    counts.index.name = 'usage_status'
    results.append(counts.reset_index())

# Combine and save
full_results = pd.concat(results, ignore_index=True)
full_results.to_csv('data/default_rate_by_loan_type.csv', index=False)

# Print the full table
print(full_results.to_string())

                            usage_status  default_rate      n       loan_type
0                          Currently use         0.539  11687           C1_10
1                             Never used         0.426    913           C1_10
2                            Used to use         0.519    511           C1_10
3                          Currently use         0.575   4400           C1_11
4                             Never used         0.488   7037           C1_11
5                            Used to use         0.591   1674           C1_11
6                          Currently use         0.484   3718           C1_12
7                             Never used         0.533   7465           C1_12
8                            Used to use         0.607   1928           C1_12
9                    Absa Bank Kenya Plc         0.391     69  C1_12ai_CHK__0
10                   Access Bank Limited         0.500     12  C1_12ai_CHK__0
11       African Banking Corporation Ltd         0.000      1  C1_12ai_CHK__0
12                    Bank of Africa Ltd         1.000      2  C1_12ai_CHK__0
13        Bank of Baroda (Kenya) Limited         0.000      2  C1_12ai_CHK__0
14     Caritas Microfinance Bank Limited         1.000      1  C1_12ai_CHK__0
15                            Citibank N         1.000      1  C1_12ai_CHK__0
16        Co-operative Bank of Kenya Ltd         0.489    620  C1_12ai_CHK__0
17    Consolidated Bank of Kenya Limited         0.333      9  C1_12ai_CHK__0
18                       Credit Bank Ltd         1.000      1  C1_12ai_CHK__0
19      Diamond Trust Bank Kenya Limited         0.515     33  C1_12ai_CHK__0
20        Donâ€™t know (DO NOT READ OUT)         0.000      2  C1_12ai_CHK__0
21                     Ecobank Kenya Ltd         1.000      1  C1_12ai_CHK__0
22                 Equity Bank Kenya Ltd         0.486   1550  C1_12ai_CHK__0
23                       Family Bank Ltd         0.511    137  C1_12ai_CHK__0
24       Faulu Microfinance Bank Limited         0.273     11  C1_12ai_CHK__0
25                     Gulf African Bank         1.000      4  C1_12ai_CHK__0
26                               HFC Ltd         0.000      2  C1_12ai_CHK__0
27                  Habib Bank AG Zurich         0.000      1  C1_12ai_CHK__0
28                        I   M Bank Ltd         0.273     11  C1_12ai_CHK__0
29                          KCB Bank Ltd         0.487   1074  C1_12ai_CHK__0
30     Kenya Women Microfinance Bank PLC         0.481     27  C1_12ai_CHK__0
31                  Kingdom Bank Limited         0.250      4  C1_12ai_CHK__0
32            M-Oriental Commercial Bank         1.000      1  C1_12ai_CHK__0
33                   NCBA Bank Kenya PLC         0.526     19  C1_12ai_CHK__0
34            National Bank of Kenya Ltd         0.475     59  C1_12ai_CHK__0
35                        Prime Bank Ltd         0.500      2  C1_12ai_CHK__0
36      Rafiki Microfinance Bank Limited         1.000      2  C1_12ai_CHK__0
37                    SBM Bank Kenya Ltd         0.000      1  C1_12ai_CHK__0
38        SMEP Microfinance Bank Limited         0.600      5  C1_12ai_CHK__0
39                       Sidian Bank Ltd         0.200     15  C1_12ai_CHK__0
40                Stanbic Bank Kenya Ltd         0.611     18  C1_12ai_CHK__0
41       Standard Chartered Bank (K) Ltd         0.450     20  C1_12ai_CHK__0
42   U &amp; I Microfinance Bank Limited         0.000      1  C1_12ai_CHK__0
43                                   nan         0.548   9393  C1_12ai_CHK__0
44                   Absa Bank Kenya Plc         0.480     25  C1_12ai_CHK__1
45                   Access Bank Limited         1.000      1  C1_12ai_CHK__1
46                    Bank of Africa Ltd         1.000      1  C1_12ai_CHK__1
47                         Bank of India         1.000      1  C1_12ai_CHK__1
48     Caritas Microfinance Bank Limited         0.500      2  C1_12ai_CHK__1
49        Co-operative Bank of Kenya Ltd         0.467     75  C1_12ai_CHK__1
50      Diamond Trust Bank Kenya Limited         0.800      5  C1_12ai_CHK__1
51                     Ecobank Kenya Ltd         0.000      1  C1_12ai_CHK__1
52                 Equity Bank Kenya Ltd         0.496    123  C1_12ai_CHK__1
53                       Family Bank Ltd         0.607     28  C1_12ai_CHK__1
54       Faulu Microfinance Bank Limited         1.000      2  C1_12ai_CHK__1
55              First Community Bank Ltd         1.000      1  C1_12ai_CHK__1
56                               HFC Ltd         1.000      1  C1_12ai_CHK__1
57                        I   M Bank Ltd         0.500      6  C1_12ai_CHK__1
58                          KCB Bank Ltd         0.538    106  C1_12ai_CHK__1
59     Kenya Women Microfinance Bank PLC         0.000      1  C1_12ai_CHK__1
60                  Kingdom Bank Limited         0.000      1  C1_12ai_CHK__1
61                   NCBA Bank Kenya PLC         0.286      7  C1_12ai_CHK__1
62            National Bank of Kenya Ltd         0.375     16  C1_12ai_CHK__1
63      Rafiki Microfinance Bank Limited         1.000      1  C1_12ai_CHK__1
64                    SBM Bank Kenya Ltd         0.000      1  C1_12ai_CHK__1
65        SMEP Microfinance Bank Limited         1.000      1  C1_12ai_CHK__1
66                       Sidian Bank Ltd         1.000      1  C1_12ai_CHK__1
67                Stanbic Bank Kenya Ltd         0.333      3  C1_12ai_CHK__1
68       Standard Chartered Bank (K) Ltd         0.400      5  C1_12ai_CHK__1
69                                   nan         0.531  12696  C1_12ai_CHK__1
70                   Absa Bank Kenya Plc         0.333      3  C1_12ai_CHK__2
71        Co-operative Bank of Kenya Ltd         0.476     21  C1_12ai_CHK__2
72      Diamond Trust Bank Kenya Limited         0.500      2  C1_12ai_CHK__2
73                     Ecobank Kenya Ltd         1.000      1  C1_12ai_CHK__2
74                 Equity Bank Kenya Ltd         0.444      9  C1_12ai_CHK__2
75                       Family Bank Ltd         0.333      3  C1_12ai_CHK__2
76       Faulu Microfinance Bank Limited         0.000      1  C1_12ai_CHK__2
77                        I   M Bank Ltd         0.000      1  C1_12ai_CHK__2
78                          KCB Bank Ltd         0.583     12  C1_12ai_CHK__2
79                   NCBA Bank Kenya PLC         0.000      1  C1_12ai_CHK__2
80            National Bank of Kenya Ltd         0.667      3  C1_12ai_CHK__2
81                       Sidian Bank Ltd         1.000      2  C1_12ai_CHK__2
82       Standard Chartered Bank (K) Ltd         0.333      3  C1_12ai_CHK__2
83                                   nan         0.530  13049  C1_12ai_CHK__2
84                   Absa Bank Kenya Plc         1.000      1  C1_12ai_CHK__3
85        Co-operative Bank of Kenya Ltd         0.000      1  C1_12ai_CHK__3
86      Diamond Trust Bank Kenya Limited         1.000      1  C1_12ai_CHK__3
87                     Ecobank Kenya Ltd         1.000      1  C1_12ai_CHK__3
88                 Equity Bank Kenya Ltd         1.000      1  C1_12ai_CHK__3
89                       Family Bank Ltd         0.500      2  C1_12ai_CHK__3
90              First Community Bank Ltd         1.000      1  C1_12ai_CHK__3
91                                   nan         0.530  13103  C1_12ai_CHK__3
92                 Equity Bank Kenya Ltd         0.000      1  C1_12ai_CHK__4
93                   NCBA Bank Kenya PLC         1.000      1  C1_12ai_CHK__4
94                                   nan         0.530  13109  C1_12ai_CHK__4
95                         Currently use         0.437   1986          C1_12a
96                            Never used         0.546  10429          C1_12a
97                           Used to use         0.557    696          C1_12a
98                         Currently use         0.528   4413          C1_12b
99                            Never used         0.522   7384          C1_12b
100                          Used to use         0.588   1314          C1_12b
101                        Currently use         0.439   1730           C1_1a
102                           Never used         0.539   9529           C1_1a
103                          Used to use         0.569   1852           C1_1a
104                        Currently use         0.644     45           C1_1b
105                           Never used         0.528  12934           C1_1b
106                          Used to use         0.659    132           C1_1b
107                        Currently use         0.543   2180            C1_2
108                           Never used         0.505   8912            C1_2
109                          Used to use         0.626   2019            C1_2
110                        Currently use         0.537   4713            C1_3
111                           Never used         0.521   6353            C1_3
112                          Used to use         0.543   2045            C1_3
113                        Currently use         0.410   1400            C1_4
114                           Never used         0.546  11100            C1_4
115                          Used to use         0.524    611            C1_4
116                        Currently use         0.527   3310            C1_5
117                           Never used         0.524   8793            C1_5
118                          Used to use         0.594   1008            C1_5
119                        Currently use         0.545    885            C1_6
120                           Never used         0.528  11837            C1_6
121                          Used to use         0.573    389            C1_6
122                        Currently use         0.508    394            C1_7
123                           Never used         0.532  12344            C1_7
124                          Used to use         0.488    373            C1_7
125                        Currently use         0.524   2253            C1_8
126                           Never used         0.539   9137            C1_8
127                          Used to use         0.489   1721            C1_8
128                        Currently use         0.345     29            C1_9
129                           Never used         0.531  13049            C1_9
130                          Used to use         0.545     33            C1_9
131                        Currently use         0.430    704          C1_13a
132                           Never used         0.540  11840          C1_13a
133                          Used to use         0.455    567          C1_13a
134                        Currently use         0.493     71          C1_13b
135                           Never used         0.530  12899          C1_13b
136                          Used to use         0.596    141          C1_13b
137                        Currently use         0.483     58          C1_13c
138                           Never used         0.531  12949          C1_13c
139                          Used to use         0.452    104          C1_13c
140                        Currently use         0.227     22           C1_14
141                           Never used         0.531  13032           C1_14
142                          Used to use         0.404     57           C1_14
143                        Currently use         0.676   1597           C1_15
144                           Never used         0.506   9922           C1_15
145                           Not stated         0.000      1           C1_15
146                          Used to use         0.537   1591           C1_15
147                        Currently use         0.606   3415           C1_16
148                           Never used         0.499   7273           C1_16
149                          Used to use         0.515   2423           C1_16
150                        Currently use         0.369    850           C1_17
151                           Never used         0.545  11846           C1_17
152                          Used to use         0.434    415           C1_17
153                        Currently use         0.612    147           C1_18
154                           Never used         0.529  12859           C1_18
155                          Used to use         0.571    105           C1_18
156                        Currently use         0.772    369           C1_19
157                           Never used         0.521  12228           C1_19
158                          Used to use         0.570    514           C1_19
159                        Currently use         0.701    137           C1_20
160                           Never used         0.528  12747           C1_20
161                          Used to use         0.524    227           C1_20
162                        Currently use         0.530   1944           C1_21
163                           Never used         0.527  10280           C1_21
164                          Used to use         0.568    887           C1_21
165                        Currently use         0.544    338           C1_22
166                           Never used         0.531  12595           C1_22
167                          Used to use         0.455    178           C1_22
168                        Currently use         0.778   4975           C1_23
169                           Never used         0.363   6538           C1_23
170                          Used to use         0.443   1598           C1_23
171                        Currently use         0.429    189           C1_24
172                           Never used         0.532  12702           C1_24
173                          Used to use         0.514    220           C1_24
174                        Currently use         0.599   2980           C1_25
175                           Never used         0.511   8322           C1_25
176                          Used to use         0.506   1809           C1_25
177                        Currently use         0.582    337           C1_26
178                           Never used         0.529  12499           C1_26
179                          Used to use         0.502    275           C1_26
180                        Currently use         0.559   5619           C1_27
181                           Never used         0.517   5561           C1_27
182                          Used to use         0.484   1931           C1_27
183                        Currently use         0.551    176           C1_28
184                           Never used         0.531  12756           C1_28
185                          Used to use         0.458    179           C1_28
186                        Currently use         0.619   1248           C1_29
187                           Never used         0.517  11153           C1_29
188                          Used to use         0.579    710           C1_29
189                        Currently use         0.500     12           C1_30
190                           Never used         0.530  13070           C1_30
191                          Used to use         0.517     29           C1_30
192                        Currently use         0.364     11           C1_31
193                           Never used         0.531  13069           C1_31
194                          Used to use         0.323     31           C1_31
195                        Currently use         0.400     85           C1_32
196                           Never used         0.532  12628           C1_32
197                           Not stated         0.500      2           C1_32
198                          Used to use         0.505    396           C1_32
199                        Currently use         0.405    353           C1_33
200                           Never used         0.534  12630           C1_33
201                           Not stated         0.500      2           C1_33
202                          Used to use         0.468    126           C1_33
203                        Currently use         0.125     24           C1_34
204                           Never used         0.531  13076           C1_34
205                           Not stated         0.500      2           C1_34
206                          Used to use         0.556      9           C1_34
207                        Currently use         0.475     40           C1_35
208                           Never used         0.531  13013           C1_35
209                           Not stated         0.500      2           C1_35
210                          Used to use         0.446     56           C1_35
211                        Currently use         0.353    447           C1_36
212                           Never used         0.536  12519           C1_36
213                           Not stated         0.500      2           C1_36
214                          Used to use         0.545    143           C1_36
215                        Currently use         0.443   2769           C1_37
216                           Never used         0.544   8389           C1_37
217                           Not stated         0.500      2           C1_37
218                          Used to use         0.593   1951           C1_37
219                        Currently use         0.384    445           C1_38
220                           Never used         0.536  12535           C1_38
221                           Not stated         0.500      2           C1_38
222                          Used to use         0.481    129           C1_38
223                        Currently use         0.380     71           C1_39
224                           Never used         0.531  13009           C1_39
225                           Not stated         0.500      2           C1_39
226                          Used to use         0.379     29           C1_39
227                        Currently use         0.418   1505           C1_40
228                           Never used         0.541  10381           C1_40
229                           Not stated         0.667      3           C1_40
230                          Used to use         0.580   1222           C1_40
231                        Currently use         0.394    246           C1_41
232                           Never used         0.533  12799           C1_41
233                           Not stated         0.667      3           C1_41
234                          Used to use         0.571     63           C1_41
235                        Currently use         0.473     55           C1_42
236                           Never used         0.531  13041           C1_42
237                           Not stated         0.667      3           C1_42
238                          Used to use         0.333     12           C1_42
239                        Currently use         0.552     58           C1_43
240                           Never used         0.530  13000           C1_43
241                           Not stated         1.000      1           C1_43
242                          Used to use         0.519     52           C1_43

In [41]:
import pandas as pd
import re

# 1. Load the variables dictionary (if not already loaded)
vars_df = pd.read_excel('../data/2024_Finaccess_Publicdata.xlsx', sheet_name='Variables')

# 2. Only keep columns matching the clean pattern C1_<number>
main_c1_cols = [c for c in modeling_df.columns if re.fullmatch(r'C1_\d+', c)]
print(f"Found {len(main_c1_cols)} main loan-type columns:\n")

# 3. Cross-reference with the Variables sheet to get readable names
c1_labels = vars_df[vars_df['name'].isin(main_c1_cols)][['name', 'varlab']]
print("--- Loan Category Dictionary ---")
print(c1_labels.to_string())
print("\n")

# 4. Re-run the default-rate table on the clean list
results = []
for col in main_c1_cols:
    counts = modeling_df.groupby(col)['defaulted'].agg(['mean', 'count']).round(3)
    counts.columns = ['default_rate', 'n']
    counts['loan_type'] = col
    
    # Optional: rename index so it says 'usage_status' like before
    counts.index.name = 'usage_status'
    results.append(counts.reset_index())

full_results = pd.concat(results, ignore_index=True)
full_results.to_csv('data/default_rate_by_loan_type_clean.csv', index=False)

print("--- Cleaned Default Rates ---")
print(full_results.to_string())

Found 41 main loan-type columns:

--- Loan Category Dictionary ---
      name                                                                            varlab
285  C1_10                                                 C1-10. Registered on Mobile money
286  C1_11                                                  C1_11. Registered on Mobile bank
287  C1_12                             C1_12. Registered on a bank/microfinance Bank account
346   C1_2                                     C1-2. Savings through mobile banking Platform
347   C1_3                               C1-3. Savings/keeping through mobile money provider
348   C1_4            C1-4. Savings at a Sacco / Savings and Credit Cooperative organisation
349   C1_5                                                          C1-5. Savings at a chama
350   C1_6                                     C1-6.   Savings with a group/group of friends
351   C1_7                                 C1-7. Savings given to a family or friend to keep
352   C1_8                                   C1-8. Savings you keep in a secret hiding place
353   C1_9                                   C1-9. Savings you keep in a Digital savings App
357  C1_14                                                                C1_14. Credit card
358  C1_15                                                   C1_15. Loan from mobile banking
359  C1_16             C1_16. Loan from mobile provider (e.g Fuliza loan, Equity's Boostika)
360  C1_17                                                            C1_17. Loan from Sacco
361  C1_18                                       C1_18. Loan from a microfinance institution
362  C1_19                                                              C1_19. Digital loans
363  C1_20                                                         C1-20. Loan from Shylocks
364  C1_21                                                    C1-21. Loan from a group/chama
365  C1_22  C1_22:Loan from a government institution foreducation, agriculture or a developm
366  C1_23                                                      C1-23 Loan from Hustler Fund
367  C1_24                                                       C1-24 Loan from an employer
368  C1_25                                          C1-25. Loan from family/friend/neighbour
369  C1_26                                                  C1-26. Cash loan from shopkeeper
370  C1_27                      C1-27. Taking goods and services on credit from a shopkeeper
371  C1_28  C1_28:Loan / credits from buyer of your harvest / supplier of agricultural input
372  C1_29                                         C1-29. Loan Lipa polepole / Hire Purchase
373  C1_30                                                        C1-30. Loan from Insurance
374  C1_31                     C1-31. Loan to buy / build a house (mortgage), or to buy land
375  C1_32                                                           C1-32. Postbank account
376  C1_33                                        C1-33. Shares /or stocks/T Bills and Bonds
377  C1_34  C1_34:Mutual Funds/ Unit Trust/ (mali, moneymarket funds) Real Estate Investment
378  C1_35                                              C1-35. Online forex/currency trading
379  C1_36                                                            C1-36. Motor insurance
380  C1_37                          C1-37.  NHIF/SHIF  Mradi wa bima ya Hospitali ya kitaifa
381  C1_38                       C1-38. Other medical/health insurance policy, NOT NHIF/SHIF
382  C1_39                           C1-39. Other insurance e.g. fire, education, crop, life
383  C1_40                                                                       C1-40. NSSF
384  C1_41                            C1-41. Employment/ Occupation pension scheme, NOT NSSF
385  C1_42                                    C1-42. Other Retirement benefits / pension pla
387  C1_43  C1_43: Digital/crypto/communitycurrencies/ virtual assets Bitcoin, Litcoin, Nuru


--- Cleaned Default Rates ---
      usage_status  default_rate      n loan_type
0    Currently use         0.539  11687     C1_10
1       Never used         0.426    913     C1_10
2      Used to use         0.519    511     C1_10
3    Currently use         0.575   4400     C1_11
4       Never used         0.488   7037     C1_11
5      Used to use         0.591   1674     C1_11
6    Currently use         0.484   3718     C1_12
7       Never used         0.533   7465     C1_12
8      Used to use         0.607   1928     C1_12
9    Currently use         0.543   2180      C1_2
10      Never used         0.505   8912      C1_2
11     Used to use         0.626   2019      C1_2
12   Currently use         0.537   4713      C1_3
13      Never used         0.521   6353      C1_3
14     Used to use         0.543   2045      C1_3
15   Currently use         0.410   1400      C1_4
16      Never used         0.546  11100      C1_4
17     Used to use         0.524    611      C1_4
18   Currently use         0.527   3310      C1_5
19      Never used         0.524   8793      C1_5
20     Used to use         0.594   1008      C1_5
21   Currently use         0.545    885      C1_6
22      Never used         0.528  11837      C1_6
23     Used to use         0.573    389      C1_6
24   Currently use         0.508    394      C1_7
25      Never used         0.532  12344      C1_7
26     Used to use         0.488    373      C1_7
27   Currently use         0.524   2253      C1_8
28      Never used         0.539   9137      C1_8
29     Used to use         0.489   1721      C1_8
30   Currently use         0.345     29      C1_9
31      Never used         0.531  13049      C1_9
32     Used to use         0.545     33      C1_9
33   Currently use         0.227     22     C1_14
34      Never used         0.531  13032     C1_14
35     Used to use         0.404     57     C1_14
36   Currently use         0.676   1597     C1_15
37      Never used         0.506   9922     C1_15
38      Not stated         0.000      1     C1_15
39     Used to use         0.537   1591     C1_15
40   Currently use         0.606   3415     C1_16
41      Never used         0.499   7273     C1_16
42     Used to use         0.515   2423     C1_16
43   Currently use         0.369    850     C1_17
44      Never used         0.545  11846     C1_17
45     Used to use         0.434    415     C1_17
46   Currently use         0.612    147     C1_18
47      Never used         0.529  12859     C1_18
48     Used to use         0.571    105     C1_18
49   Currently use         0.772    369     C1_19
50      Never used         0.521  12228     C1_19
51     Used to use         0.570    514     C1_19
52   Currently use         0.701    137     C1_20
53      Never used         0.528  12747     C1_20
54     Used to use         0.524    227     C1_20
55   Currently use         0.530   1944     C1_21
56      Never used         0.527  10280     C1_21
57     Used to use         0.568    887     C1_21
58   Currently use         0.544    338     C1_22
59      Never used         0.531  12595     C1_22
60     Used to use         0.455    178     C1_22
61   Currently use         0.778   4975     C1_23
62      Never used         0.363   6538     C1_23
63     Used to use         0.443   1598     C1_23
64   Currently use         0.429    189     C1_24
65      Never used         0.532  12702     C1_24
66     Used to use         0.514    220     C1_24
67   Currently use         0.599   2980     C1_25
68      Never used         0.511   8322     C1_25
69     Used to use         0.506   1809     C1_25
70   Currently use         0.582    337     C1_26
71      Never used         0.529  12499     C1_26
72     Used to use         0.502    275     C1_26
73   Currently use         0.559   5619     C1_27
74      Never used         0.517   5561     C1_27
75     Used to use         0.484   1931     C1_27
76   Currently use         0.551    176     C1_28
77      Never used         0.531  12756     C1_28
78     Used to use         0.458    179     C1_28
79   Currently use         0.619   1248     C1_29
80      Never used         0.517  11153     C1_29
81     Used to use         0.579    710     C1_29
82   Currently use         0.500     12     C1_30
83      Never used         0.530  13070     C1_30
84     Used to use         0.517     29     C1_30
85   Currently use         0.364     11     C1_31
86      Never used         0.531  13069     C1_31
87     Used to use         0.323     31     C1_31
88   Currently use         0.400     85     C1_32
89      Never used         0.532  12628     C1_32
90      Not stated         0.500      2     C1_32
91     Used to use         0.505    396     C1_32
92   Currently use         0.405    353     C1_33
93      Never used         0.534  12630     C1_33
94      Not stated         0.500      2     C1_33
95     Used to use         0.468    126     C1_33
96   Currently use         0.125     24     C1_34
97      Never used         0.531  13076     C1_34
98      Not stated         0.500      2     C1_34
99     Used to use         0.556      9     C1_34
100  Currently use         0.475     40     C1_35
101     Never used         0.531  13013     C1_35
102     Not stated         0.500      2     C1_35
103    Used to use         0.446     56     C1_35
104  Currently use         0.353    447     C1_36
105     Never used         0.536  12519     C1_36
106     Not stated         0.500      2     C1_36
107    Used to use         0.545    143     C1_36
108  Currently use         0.443   2769     C1_37
109     Never used         0.544   8389     C1_37
110     Not stated         0.500      2     C1_37
111    Used to use         0.593   1951     C1_37
112  Currently use         0.384    445     C1_38
113     Never used         0.536  12535     C1_38
114     Not stated         0.500      2     C1_38
115    Used to use         0.481    129     C1_38
116  Currently use         0.380     71     C1_39
117     Never used         0.531  13009     C1_39
118     Not stated         0.500      2     C1_39
119    Used to use         0.379     29     C1_39
120  Currently use         0.418   1505     C1_40
121     Never used         0.541  10381     C1_40
122     Not stated         0.667      3     C1_40
123    Used to use         0.580   1222     C1_40
124  Currently use         0.394    246     C1_41
125     Never used         0.533  12799     C1_41
126     Not stated         0.667      3     C1_41
127    Used to use         0.571     63     C1_41
128  Currently use         0.473     55     C1_42
129     Never used         0.531  13041     C1_42
130     Not stated         0.667      3     C1_42
131    Used to use         0.333     12     C1_42
132  Currently use         0.552     58     C1_43
133     Never used         0.530  13000     C1_43
134     Not stated         1.000      1     C1_43
135    Used to use         0.519     52     C1_43